from .main import *
from .config import *
from .ocr import *
from .processing import *
from .ctpn_model import *
from .classify import *
from .ctpn_utils import *
from .ctpn_predict import *
from .idCard_class import *
from .studentCard_class import *
from .drivingLicense_class import *
