# Generated by Django 3.2.4 on 2021-06-21 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
