# Generated by Django 3.2.4 on 2021-06-22 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0002_images_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='name',
        ),
        migrations.AddField(
            model_name='images',
            name='result',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
