# Generated by Django 3.2.4 on 2021-06-25 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0003_auto_20210626_0011'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentCard',
            new_name='Student_Card',
        ),
    ]
