# Generated by Django 3.2.4 on 2021-07-20 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0006_auto_20210626_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='driving_license_card',
            name='expires',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='idcard',
            name='expires',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
